# Generated by Django 3.2 on 2022-04-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fav_icecream_flavour',
            field=models.CharField(choices=[('1', 'Chocolate'), ('2', 'Vanilla'), ('3', 'Strawberry'), ('4', 'Mint Chocolate Chip'), ('5', 'Butter Pecan'), ('6', 'Cookies-n-cream'), ('7', 'Cherry'), ('8', 'Rocky Road')], max_length=30),
        ),
    ]
