# Generated by Django 4.0.4 on 2022-05-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('emial', models.EmailField(max_length=100)),
                ('number', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=200)),
                ('roll', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=15)),
                ('favIceCol', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
            ],
        ),
    ]
